run:
  name: local-demo-run
  project_manifest: ../gauntlet-sandbox/gauntlet.yaml
  prompt_file: raw_input.txt

input:
  dataset_path: ../input_data/Teen_Mental_Health_Dataset.csv

execution:
  mode: sandbox_only
  selected_steps:
    - data_loader
    - data_preprocessing
    - analysis
    - train
    - eval
    - visualization
